import { relations, sql } from "drizzle-orm";
import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const jobStatus = pgEnum("job_status", ["discovered", "saved", "evaluating", "rejected", "applying", "applied", "interviewing", "offered", "accepted", "declined", "archived"]);
export const claimState = pgEnum("claim_state", ["user_approved", "ai_suggested", "unsupported", "archived"]);
export const artifactState = pgEnum("artifact_state", ["draft", "approved", "archived"]);

export const users = pgTable("users", { id: uuid("id").primaryKey().defaultRandom(), email: text("email").notNull().unique(), name: text("name"), image: text("image"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const profiles = pgTable("profiles", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: text("title").notNull(), summary: text("summary").default("").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => ({ userIdx: index("profiles_user_idx").on(t.userId) }));
export const profileSections = pgTable("profile_sections", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), profileId: uuid("profile_id").notNull().references(() => profiles.id, { onDelete: "cascade" }), kind: text("kind").notNull(), content: jsonb("content").notNull(), claimState: claimState("claim_state").default("user_approved").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const evidenceItems = pgTable("evidence_items", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), profileId: uuid("profile_id").notNull().references(() => profiles.id, { onDelete: "cascade" }), sourceType: text("source_type").notNull(), title: text("title").notNull(), content: text("content").notNull(), claimState: claimState("claim_state").default("user_approved").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const jobPostings = pgTable("job_postings", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), canonicalUrl: text("canonical_url"), title: text("title").notNull(), company: text("company").notNull(), location: text("location"), description: text("description").notNull(), status: jobStatus("status").default("discovered").notNull(), contentHash: text("content_hash"), notes: text("notes"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => ({ userIdx: index("jobs_user_idx").on(t.userId), dedupeIdx: uniqueIndex("jobs_user_url_unique").on(t.userId, t.canonicalUrl) }));
export const jobSearches = pgTable("job_searches", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), query: text("query").notNull(), filters: jsonb("filters").notNull().default(sql`'{}'::jsonb`), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const fitEvaluations = pgTable("fit_evaluations", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), profileId: uuid("profile_id").notNull().references(() => profiles.id), jobId: uuid("job_id").notNull().references(() => jobPostings.id, { onDelete: "cascade" }), score: integer("score").notNull(), confidence: text("confidence").notNull(), dealBreaker: boolean("deal_breaker").default(false).notNull(), recommendation: text("recommendation").notNull(), explanation: jsonb("explanation").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const applications = pgTable("applications", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), profileId: uuid("profile_id").notNull().references(() => profiles.id), jobId: uuid("job_id").notNull().references(() => jobPostings.id, { onDelete: "cascade" }), status: jobStatus("status").default("applying").notNull(), appliedAt: timestamp("applied_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const applicationArtifacts = pgTable("application_artifacts", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), applicationId: uuid("application_id").notNull().references(() => applications.id, { onDelete: "cascade" }), artifactType: text("artifact_type").notNull(), version: integer("version").notNull(), content: text("content").notNull(), sourceRefs: jsonb("source_refs").notNull(), state: artifactState("state").default("draft").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const interviewPreps = pgTable("interview_preps", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), applicationId: uuid("application_id").notNull().references(() => applications.id, { onDelete: "cascade" }), version: integer("version").notNull(), content: jsonb("content").notNull(), notes: text("notes"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const outcomes = pgTable("outcomes", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), applicationId: uuid("application_id").notNull().references(() => applications.id, { onDelete: "cascade" }), stage: text("stage").notNull(), result: text("result").notNull(), feedback: text("feedback"), compensationNotes: text("compensation_notes"), followUpAt: timestamp("follow_up_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const auditEvents = pgTable("audit_events", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id"), metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });

export const userRelations = relations(users, ({ many }) => ({ profiles: many(profiles), jobs: many(jobPostings), applications: many(applications) }));
