CREATE TYPE job_status AS ENUM ('discovered','saved','evaluating','rejected','applying','applied','interviewing','offered','accepted','declined','archived');
CREATE TYPE claim_state AS ENUM ('user_approved','ai_suggested','unsupported','archived');
CREATE TYPE artifact_state AS ENUM ('draft','approved','archived');

CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, name text, image text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, title text NOT NULL, summary text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX profiles_user_idx ON profiles(user_id);
CREATE TABLE profile_sections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, kind text NOT NULL, content jsonb NOT NULL, claim_state claim_state NOT NULL DEFAULT 'user_approved', updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE evidence_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, source_type text NOT NULL, title text NOT NULL, content text NOT NULL, claim_state claim_state NOT NULL DEFAULT 'user_approved', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE job_postings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, canonical_url text, title text NOT NULL, company text NOT NULL, location text, description text NOT NULL, status job_status NOT NULL DEFAULT 'discovered', content_hash text, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX jobs_user_idx ON job_postings(user_id);
CREATE UNIQUE INDEX jobs_user_url_unique ON job_postings(user_id, canonical_url);
CREATE TABLE job_searches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, query text NOT NULL, filters jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE fit_evaluations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, profile_id uuid NOT NULL REFERENCES profiles(id), job_id uuid NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE, score integer NOT NULL, confidence text NOT NULL, deal_breaker boolean NOT NULL DEFAULT false, recommendation text NOT NULL, explanation jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE applications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, profile_id uuid NOT NULL REFERENCES profiles(id), job_id uuid NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE, status job_status NOT NULL DEFAULT 'applying', applied_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE application_artifacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, application_id uuid NOT NULL REFERENCES applications(id) ON DELETE CASCADE, artifact_type text NOT NULL, version integer NOT NULL, content text NOT NULL, source_refs jsonb NOT NULL, state artifact_state NOT NULL DEFAULT 'draft', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE interview_preps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, application_id uuid NOT NULL REFERENCES applications(id) ON DELETE CASCADE, version integer NOT NULL, content jsonb NOT NULL, notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE outcomes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, application_id uuid NOT NULL REFERENCES applications(id) ON DELETE CASCADE, stage text NOT NULL, result text NOT NULL, feedback text, compensation_notes text, follow_up_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE SET NULL, action text NOT NULL, entity_type text NOT NULL, entity_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
