"use client";
import Link from "next/link";
import { useState } from "react";
import { useJourney } from "../journey/JourneyProvider";
import { getHighestPriorityAction, getPipelineCounts, statusLabels } from "../journey/selectors";
import type { JourneyStatus } from "../journey/types";
import { StatusBadge } from "../ui/Primitives";
const statuses:JourneyStatus[]=["discovered","shortlisted","applying","submitted","interviewing","offer","accepted","closed"];
export function CareerDashboardPage(){const {state}=useJourney(); const [stage,setStage]=useState<JourneyStatus|"all">("all"); const next=getHighestPriorityAction(state); const counts=getPipelineCounts(state); const roles=state.roles.filter(r=>stage==="all"||r.status===stage); return <><section className="cj-page-head career-container"><h1>Home</h1><p>Alex is tracking {state.roles.length} fixture roles with one shared browser-local journey state.</p>{next&&<article className="cj-hero-card dashboard-next-action"><div><p className="dashboard-next-action-kicker">Next best action</p><h2>{next.label}</h2><p className="dashboard-next-action-meta">{next.role?.title} · {next.role?.company}</p></div><Link className="career-btn" href={next.href}>{next.label}</Link></article>}</section><section className="career-container cj-grid"><article className="cj-card cj-span"><h2>Pipeline</h2><div className="cj-pipeline"><button onClick={()=>setStage("all")}>All {state.roles.length}</button>{statuses.map(s=><button key={s} aria-pressed={stage===s} onClick={()=>setStage(s)}>{statusLabels[s]} {counts[s]??0}</button>)}</div><div className="cj-list">{roles.map(r=><Link key={r.id} href={`/jobs/${r.id}`}><StatusBadge status={r.status}/>{r.title} · {r.company}</Link>)}</div></article><article className="cj-card"><h2>Upcoming</h2>{state.interviews.map(i=>{const r=state.roles.find(x=>x.id===i.roleId); return <p key={i.id}><Link href={`/interviews/${i.id}`}>{r?.company} {i.stage}</Link><br/><span>{new Date(i.when).toLocaleDateString()}</span></p>})}</article><article className="cj-card"><h2>Shortlisted roles</h2>{state.roles.filter(r=>r.status==="shortlisted").map(r=><p key={r.id}><Link href={`/jobs/${r.id}`}>{r.title}</Link> closes {r.closingDate}</p>)}<Link href="/saved">Compare shortlist</Link></article><article className="cj-card cj-span"><h2>Recent activity</h2><ul>{state.roles.slice().sort((a,b)=>a.lastActivity.localeCompare(b.lastActivity)).slice(0,5).map(r=><li key={r.id}>{r.lastActivity}: {r.title}</li>)}</ul></article></section></>}
